#!/bin/zsh
# Install (or remove) the Claude Meter token pipeline as macOS launchd agents.
#
#   host/macos/install.sh            install + start both agents
#   host/macos/install.sh uninstall  stop + remove them
#   host/macos/install.sh status     show agent state and the last log lines
#
# Agents (run as you, from this checkout -- no copies to keep in sync):
#   com.claude-meter.token-push       push_claude_token.py every 4 h + at login
#   com.claude-meter.notify-listener  notify_listener.py on :5555, kept alive;
#                                     the meter pings it when it needs a token
#   com.claude-meter.brain            brain_server.py on :5556, kept alive: what
#                                     "Jarvis" can't answer offline (whisper +
#                                     claude -p). Needs: brew install whisper-cpp
#                                     + the model (fetched below if missing)
#
# The Mac counterpart of host/linux/*.service|timer.
set -e
REPO="${0:A:h:h:h}"
AGENTS="$HOME/Library/LaunchAgents"
LOGS="$HOME/Library/Logs"
PY=/usr/bin/python3                # stable path: survives Homebrew upgrades
CLAUDE_BIN="$HOME/.local/bin/claude"
PUSH=com.claude-meter.token-push
LISTEN=com.claude-meter.notify-listener
BRAIN=com.claude-meter.brain
WHISPER_MODEL="$HOME/.cache/claude-meter/ggml-small.en.bin"
UID_=$(id -u)

plist() {   # label, script, extra-xml
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by host/macos/install.sh — edit that, not this. -->
<plist version="1.0">
<dict>
    <key>Label</key><string>$1</string>
    <key>ProgramArguments</key>
    <array><string>$PY</string><string>$REPO/$2</string></array>
    <key>WorkingDirectory</key><string>$REPO</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>CLAUDE_BIN</key><string>$CLAUDE_BIN</string>
        <key>PATH</key><string>$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
    </dict>
    <key>StandardOutPath</key><string>$LOGS/$1.log</string>
    <key>StandardErrorPath</key><string>$LOGS/$1.log</string>
    <key>RunAtLoad</key><true/>
$3
</dict>
</plist>
EOF
}

unload() { launchctl bootout "gui/$UID_/$1" 2>/dev/null || true; }

case "${1:-install}" in
install)
  [[ -x "$CLAUDE_BIN" ]] || echo "warning: $CLAUDE_BIN not found — token refresh will fail"
  mkdir -p "$AGENTS" "$LOGS"
  plist $PUSH push_claude_token.py \
    "    <key>StartInterval</key><integer>14400</integer>" > "$AGENTS/$PUSH.plist"
  plist $LISTEN notify_listener.py \
    "    <key>KeepAlive</key><true/>
    <key>ThrottleInterval</key><integer>10</integer>" > "$AGENTS/$LISTEN.plist"
  plist $BRAIN brain_server.py \
    "    <key>KeepAlive</key><true/>
    <key>ThrottleInterval</key><integer>10</integer>" > "$AGENTS/$BRAIN.plist"
  command -v whisper-cli >/dev/null || [[ -x /opt/homebrew/bin/whisper-cli ]] || echo "warning: whisper-cli missing — brew install whisper-cpp"
  if [[ ! -f "$WHISPER_MODEL" ]]; then
    echo "fetching the whisper model (~470 MB)..."
    mkdir -p "${WHISPER_MODEL:h}"
    curl -sL -o "$WHISPER_MODEL" https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-small.en.bin
  fi
  for a in $LISTEN $PUSH $BRAIN; do
    unload $a
    launchctl bootstrap "gui/$UID_" "$AGENTS/$a.plist"
    echo "loaded $a"
  done
  echo "logs: $LOGS/$PUSH.log, $LOGS/$LISTEN.log, $LOGS/$BRAIN.log"
  echo "First run: if macOS asks whether 'security' may read \"Claude Code-credentials\", choose Always Allow."
  ;;
uninstall)
  for a in $PUSH $LISTEN $BRAIN; do unload $a; rm -f "$AGENTS/$a.plist"; echo "removed $a"; done
  ;;
status)
  for a in $LISTEN $PUSH $BRAIN; do
    echo "== $a"; launchctl print "gui/$UID_/$a" 2>/dev/null | grep -E "state =|last exit code|runs =" || echo "not loaded"
    tail -n 5 "$LOGS/$a.log" 2>/dev/null
  done
  ;;
*) echo "usage: $0 [install|uninstall|status]"; exit 2 ;;
esac
