#!/usr/bin/env python3
"""Pack Clawd pixel-art animations (claudepix JSON) into main/clawd_anims.h.

Source data: the claudepix scrape in the sibling Clawdmeter project
(../Claude_Meter_HY3/tools/claudepix_data). Each animation is a list of 20x20
palette-indexed frames with a per-frame hold time. Cells are packed two per
byte (4 bits, high nibble first) -> 200 bytes per frame.

    python3 tools/gen_clawd.py [SRC_DIR]

R2-D2 (the AiPi's splash) is appended from tools/r2_pix.py, same shape.

Do not edit the generated header by hand; re-run this instead.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import r2_pix  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRC = os.path.join(HERE, "..", "..", "Claude_Meter_HY3", "tools", "claudepix_data")
OUT = os.path.join(HERE, "..", "main", "clawd_anims.h")

# (enum suffix, source file) — order defines the enum.
ANIMS = [
    ("IDLE_BLINK",       "idle_blink.json"),
    ("IDLE_BREATHE",     "idle_breathe.json"),
    ("LOOK_AROUND",      "idle_look_around.json"),
    ("CODING",           "work_coding.json"),
    ("THINK",            "work_think.json"),
    ("SURPRISE",         "expression_surprise.json"),
    ("SLEEP",            "expression_sleep.json"),
    ("WINK",             "expression_wink.json"),
    ("DANCE_BOUNCE",     "dance_bounce.json"),
    ("DANCE_SWAY",       "dance_sway.json"),
]


def hex_rgb(s):
    s = s.lstrip("#")
    if len(s) == 3:
        s = "".join(c * 2 for c in s)
    return int(s, 16)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    out = ["/* Generated by tools/gen_clawd.py -- do not edit. */",
           "/* Clawd pixel-art animations (source: claudepix, via Claude_Meter_HY3) + R2-D2 (tools/r2_pix.py). */",
           "#pragma once", "#include <stdint.h>", "",
           "#define CLAWD_GRID 20", "#define CLAWD_FRAME_BYTES 200", "",
           "typedef struct {",
           "    const char     *name;",
           "    uint8_t         ncolors;     /* palette[0] is transparent */",
           "    const uint32_t *palette;     /* 0xRRGGBB */",
           "    uint16_t        nframes;",
           "    const uint8_t (*frames)[CLAWD_FRAME_BYTES];",
           "    const uint16_t *holds;       /* ms per frame */",
           "} clawd_anim_t;", "",
           "typedef enum {"]
    data = [(name, json.load(open(os.path.join(src, fn)))) for name, fn in ANIMS]
    data += list(r2_pix.ANIMS.items())
    out += [f"    CLAWD_{name}," for name, _ in data]
    out += ["    CLAWD_COUNT", "} clawd_anim_id_t;", ""]

    total = 0
    for name, d in data:
        fn = d["name"]
        pal = d["palette"]
        assert len(pal) <= 16, fn
        frames = d["frames"]
        low = name.lower()
        cols = ", ".join("0x000000" if p == "transparent" else f"0x{hex_rgb(p):06X}" for p in pal)
        out.append(f"static const uint32_t clawd_{low}_pal[] = {{{cols}}};")
        out.append(f"static const uint16_t clawd_{low}_holds[] = {{{', '.join(str(f['hold']) for f in frames)}}};")
        out.append(f"static const uint8_t clawd_{low}_frames[{len(frames)}][CLAWD_FRAME_BYTES] = {{")
        for f in frames:
            g = f["grid"]
            assert len(g) == 20 and all(len(r) == 20 for r in g), fn
            cells = [c for row in g for c in row]
            packed = [(cells[i] << 4) | cells[i + 1] for i in range(0, 400, 2)]
            out.append("    {" + ",".join(str(b) for b in packed) + "},")
        out.append("};")
        out.append("")
        total += len(frames) * 200

    out.append("static const clawd_anim_t clawd_anims[CLAWD_COUNT] = {")
    for name, d in data:
        low = name.lower()
        n = len(d["frames"])
        out.append(f'    [CLAWD_{name}] = {{"{low}", sizeof(clawd_{low}_pal)/4, clawd_{low}_pal, {n}, '
                   f"clawd_{low}_frames, clawd_{low}_holds}},")
    out.append("};")
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(data)} animations, {total} bytes of frame data")


if __name__ == "__main__":
    main()
